---
- name: Playbook Orchestration
  hosts: localhost
  connection: local
  gather_facts: false
  roles: 
    - infra_setup
  tasks:
    - name: remove known hosts
      raw: ssh-keygen -R "{{get_elastic_ip.addresses[0].public_ip}}"

# - name: Jenkins configuration
#   hosts: ec2hosts
#   become: yes
#   remote_user: ubuntu
#   gather_facts: false
#   vars:
#     ansible_ssh_private_key_file: "~/jenkinskey"
#   roles:
#     - jenkins_configuration
    